### ISSUE TITLE
node-gyp rebuild fails on Elastic Beanstalk

### ISSUE THREAD

**Issue by geoyws** [websockets/bufferutil#51] opened 2016-09-23 08:05 UTC
> 1601 verbose rebuild bundle /tmp/deployment/application/node_modules/buffer-writer
> 1602 info build /tmp/deployment/application/node_modules/buffer-writer
> 1603 info preinstall buffer-writer@1.0.1
> 1604 info linkStuff buffer-writer@1.0.1
> 1605 silly linkStuff buffer-writer@1.0.1 has /tmp/deployment/application/node_modules as its parent node_modules
> 1606 verbose linkBins buffer-writer@1.0.1
> 1607 verbose linkMans buffer-writer@1.0.1
> 1608 verbose rebuildBundles buffer-writer@1.0.1
> 1609 info install buffer-writer@1.0.1
> 1610 info postinstall buffer-writer@1.0.1
> 1611 verbose rebuild bundle /tmp/deployment/application/node_modules/bufferutil
> 1612 info build /tmp/deployment/application/node_modules/bufferutil
> 1613 info preinstall bufferutil@1.2.1
> 1614 info linkStuff bufferutil@1.2.1
> 1615 silly linkStuff bufferutil@1.2.1 has /tmp/deployment/application/node_modules as its parent node_modules
> 1616 verbose linkBins bufferutil@1.2.1
> 1617 verbose linkMans bufferutil@1.2.1
> 1618 verbose rebuildBundles bufferutil@1.2.1
> 1619 info install bufferutil@1.2.1
> 1620 verbose unsafe-perm in lifecycle false
> 1621 info bufferutil@1.2.1 Failed to exec install script
> 1622 verbose stack Error: bufferutil@1.2.1 install: `node-gyp rebuild`
> 1622 verbose stack Exit status 1
> 1622 verbose stack     at EventEmitter.<anonymous> (/opt/elasticbeanstalk/node-install/node-v4.4.6-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
> 1622 verbose stack     at emitTwo (events.js:87:13)
> 1622 verbose stack     at EventEmitter.emit (events.js:172:7)
> 1622 verbose stack     at ChildProcess.<anonymous> (/opt/elasticbeanstalk/node-install/node-v4.4.6-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:24:14)
> 1622 verbose stack     at emitTwo (events.js:87:13)
> 1622 verbose stack     at ChildProcess.emit (events.js:172:7)
> 1622 verbose stack     at maybeClose (internal/child_process.js:827:16)
> 1622 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 1623 verbose pkgid bufferutil@1.2.1
> 1624 verbose cwd /tmp/deployment/application
> 1625 error Linux 4.4.14-24.50.amzn1.x86_64
> 1626 error argv "/opt/elasticbeanstalk/node-install/node-v4.4.6-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v4.4.6-linux-x64/bin/npm" "--production" "install"
> 1627 error node v4.4.6
> 1628 error npm  v2.15.5
> 1629 error code ELIFECYCLE
> 1630 error bufferutil@1.2.1 install: `node-gyp rebuild`
> 1630 error Exit status 1
> 1631 error Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
> 1631 error This is most likely a problem with the bufferutil package,
> 1631 error not with npm itself.
> 1631 error Tell the author that this fails on your system:
> 1631 error     node-gyp rebuild
> 1631 error You can get information on how to open an issue for this project with:
> 1631 error     npm bugs bufferutil
> 1631 error Or if that isn't available, you can get their info via:
> 1631 error
> 1631 error     npm owner ls bufferutil
> 1631 error There is likely additional logging output above.
> 1632 verbose exit [ 1, true ]

Not sure if I'm missing something.

**Comment by lpinca** [comment] 2016-11-27 08:35
Possible dupe of #30.

**Comment by lpinca** [comment] 2017-02-07 17:46
Closing as there are now pre-built binaries which are downloaded and installed with npm.
Please reopen, if the problem persists.

**Closed by lpinca** 2017-02-07 17:46 UTC
